"""Schemas 聚合。"""

from app.schemas.album import (
    AlbumAlignTrackResult,
    AlbumAlignTracksRequest,
    AlbumAlignTracksResult,
    AlbumBrief,
    AlbumCreate,
    AlbumExternalCandidate,
    AlbumFuzzyHit,
    AlbumImportPreviewItem,
    AlbumImportReviewCandidate,
    AlbumImportReviewVideo,
    AlbumImportTrackItem,
    AlbumImportTrackResult,
    AlbumImportTracksRequest,
    AlbumImportTracksResult,
    AlbumRead,
    AlbumTrackCreate,
    AlbumTrackDetailRead,
    AlbumTracklist,
    AlbumTracklistItem,
    AlbumTrackRead,
    AlbumUpdate,
    CoverApplyRequest,
    CoverSearchItem,
    CoverSearchRequest,
)
from app.schemas.ai import AiSuggestRequest, AiSuggestResult
from app.schemas.artist import (
    ArtistBrief,
    ArtistCreate,
    ArtistFuzzyHit,
    ArtistRead,
    ArtistUpdate,
)
from app.schemas.common import MessageResponse, ORMModel, PageResponse
from app.schemas.playback import (
    PlaybackSessionCreate,
    PlaybackSessionRead,
    PlaybackSessionWindow,
    TranscodeSessionInfo,
)
from app.schemas.provider import (
    FetchExternalRequest,
    FetchExternalResult,
    ProviderDetail,
    ProviderSearchItem,
)
from app.schemas.entity_lock import EntityLocksRead, EntityLocksUpdate
from app.schemas.db_views import (
    ArtistWorkspaceResponse,
    GroupListResponse,
    GroupListRow,
    GroupMemberRow,
    GroupCompanyRow,
    GroupIssueCount,
)
from app.schemas.data_health import (
    DataHealthReport,
    HealthCheckSummary,
    HealthCounts,
    HealthEntityStats,
    HealthIssue,
)
from app.schemas.company import (
    ArtistCompanyRelationCreate,
    ArtistCompanyRelationRead,
    CompanyBrief,
    CompanyCreate,
    CompanyRead,
    CompanyRelationMember,
    CompanyRelationsRead,
    CompanyUpdate,
    GroupCompanyRelationCreate,
    GroupCompanyRelationRead,
)
from app.schemas.dashboard import (
    DashboardStats,
    LibraryStats,
    StatsOverview,
    StatsRankItem,
    StatsWatchBlock,
    StorageUsage,
    WatchPingRequest,
    WatchPingResult,
)
from app.schemas.recycle import RecycleItem
from app.schemas.group import (
    GroupBrief,
    GroupCreate,
    GroupFuzzyHit,
    GroupRead,
    GroupSubUnitBrief,
    GroupUpdate,
)
from app.schemas.membership import (
    MembershipCreate,
    MembershipRead,
    MembershipReadWithArtist,
    MembershipReadWithGroup,
    MembershipUpdate,
)
from app.schemas.music_video import (
    BuildTitleRequest,
    BuildTitleResult,
    FolderBrowseResult,
    FolderChild,
    IncomingInfoItem,
    IncomingInfoRequest,
    IngestRequest,
    IngestResult,
    LibraryCleanupResult,
    MatchHintEntity,
    MatchHintsResult,
    MatchHintTrack,
    MissingVideoItem,
    MusicVideoBrief,
    MusicVideoCreate,
    MusicVideoRead,
    MusicVideoTrackInput,
    MusicVideoTrackRead,
    MusicVideoUpdate,
    CoverFrameApplyRequest,
    CoverFrameItem,
    CoverFramesRequest,
    CoverFramesResponse,
    FocusResponse,
    PathPreviewRequest,
    PathPreviewResult,
    ReorganizeExecuteRequest,
    ReorganizeMoveResult,
    ReorganizePlanItem,
    ReorganizeResult,
    ResolutionFacet,
    ResolutionFacetResponse,
    ScannedFileItem,
    VideoPathSuggestion,
    VideoRelocateRequest,
    VideoRelocateResult,
)
from app.schemas.photo import (
    PhotoCollectRequest,
    PhotoCollectionCreate,
    PhotoCollectionRead,
    PhotoCollectionUpdate,
    PhotoFeedItem,
    PhotoFeedResponse,
    PhotoMembershipsResponse,
    PhotoRead,
    PhotoScanResult,
    PhotoSourceCreate,
    PhotoSourceRead,
)
from app.schemas.song import (
    CreditsCreate,
    CreditsRead,
    SongArtistRelationCreate,
    SongArtistRelationRead,
    SongBrief,
    SongCreate,
    SongFuzzyHit,
    SongRead,
    SongUpdate,
)

__all__ = [
    "ORMModel",
    "PageResponse",
    "MessageResponse",
    # Artist
    "ArtistCreate",
    "ArtistRead",
    "ArtistUpdate",
    "ArtistBrief",
    "ArtistFuzzyHit",
    # Group
    "GroupCreate",
    "GroupRead",
    "GroupUpdate",
    "GroupBrief",
    "GroupSubUnitBrief",
    "GroupFuzzyHit",
    # Membership
    "MembershipCreate",
    "MembershipRead",
    "MembershipReadWithArtist",
    "MembershipReadWithGroup",
    "MembershipUpdate",
    # Company
    "CompanyCreate",
    "CompanyRead",
    "CompanyUpdate",
    "CompanyBrief",
    "ArtistCompanyRelationCreate",
    "ArtistCompanyRelationRead",
    "GroupCompanyRelationCreate",
    "GroupCompanyRelationRead",
    "CompanyRelationMember",
    "CompanyRelationsRead",
    # Album
    "AlbumCreate",
    "AlbumRead",
    "AlbumUpdate",
    "AlbumBrief",
    "AlbumFuzzyHit",
    "AlbumAlignTrackResult",
    "AlbumAlignTracksRequest",
    "AlbumAlignTracksResult",
    "AlbumTrackCreate",
    "AlbumTrackDetailRead",
    "AlbumTrackRead",
    "AlbumExternalCandidate",
    "AlbumTracklist",
    "AlbumTracklistItem",
    "AlbumImportTrackItem",
    "AlbumImportPreviewItem",
    "AlbumImportReviewCandidate",
    "AlbumImportReviewVideo",
    "AlbumImportTracksRequest",
    "AlbumImportTrackResult",
    "AlbumImportTracksResult",
    "CoverSearchRequest",
    "CoverSearchItem",
    "CoverApplyRequest",
    # Song
    "SongCreate",
    "SongRead",
    "SongUpdate",
    "SongBrief",
    "SongFuzzyHit",
    "SongArtistRelationCreate",
    "SongArtistRelationRead",
    "CreditsCreate",
    "CreditsRead",
    # MusicVideo
    "MusicVideoCreate",
    "MusicVideoRead",
    "MusicVideoUpdate",
    "MusicVideoBrief",
    "MusicVideoTrackInput",
    "MusicVideoTrackRead",
    "ScannedFileItem",
    "MatchHintEntity",
    "MatchHintsResult",
    "MatchHintTrack",
    "CoverFrameApplyRequest",
    "CoverFrameItem",
    "CoverFramesRequest",
    "CoverFramesResponse",
    "FocusResponse",
    "IngestRequest",
    "IngestResult",
    "IncomingInfoRequest",
    "IncomingInfoItem",
    "PathPreviewRequest",
    "PathPreviewResult",
    "ReorganizePlanItem",
    "ReorganizeExecuteRequest",
    "ReorganizeMoveResult",
    "ReorganizeResult",
    "ResolutionFacet",
    "ResolutionFacetResponse",
    "BuildTitleRequest",
    "BuildTitleResult",
    "VideoPathSuggestion",
    "VideoRelocateRequest",
    "VideoRelocateResult",
    "MissingVideoItem",
    "LibraryCleanupResult",
    # Photos
    "PhotoSourceCreate",
    "PhotoSourceRead",
    "PhotoScanResult",
    "PhotoRead",
    "PhotoFeedItem",
    "PhotoFeedResponse",
    "PhotoCollectionCreate",
    "PhotoCollectionUpdate",
    "PhotoCollectionRead",
    "PhotoCollectRequest",
    "PhotoMembershipsResponse",
    # AI
    "AiSuggestRequest",
    "AiSuggestResult",
    # 站点获取（Provider）
    "ProviderSearchItem",
    "ProviderDetail",
    "FetchExternalRequest",
    "FetchExternalResult",
    # 实体字段锁
    "EntityLocksRead",
    "EntityLocksUpdate",
    # 数据体检
    "DataHealthReport",
    # 新版资料库视图
    "ArtistWorkspaceResponse",
    "GroupListResponse",
    "GroupListRow",
    "GroupMemberRow",
    "GroupCompanyRow",
    "GroupIssueCount",
    "HealthCheckSummary",
    "HealthCounts",
    "HealthEntityStats",
    "HealthIssue",
    # Playback
    "PlaybackSessionCreate",
    "PlaybackSessionRead",
    "PlaybackSessionWindow",
    "TranscodeSessionInfo",
    # Dashboard
    "DashboardStats",
    "StorageUsage",
    "StatsOverview",
    "StatsRankItem",
    "StatsWatchBlock",
    "LibraryStats",
]
